name: example-environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=39
  - psutil
  - toolz
  - dill
  - partd
  - bokeh
  - dask
  - pip
  - pip:
    - plotly 
    - pandas
    - matplotlib
    - scikit-learn
    - numpy
